### PR TITLE
[10.0] [MIG] [WIP] connector_prestashop: Migration to v 10.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
This PR is work in progress.
Thanks!!

### CODE REVIEW

**Comment by florian-dacosta** [comment]
The connector is beeing refactored here : https://github.com/OCA/connector/pull/231
I guess it will change a lot of thing in the connector-prestashop, so I wonder, should the PR on connector wait a few month to target new odoo version?
Or should the work on prestashop stand by?
Else, the connector-prestashop won't work anymore when the PR on connector is merged.
Or maybe it is acceptable to have the connector-prestashop work with a specific commit of the connector...

Same problem goes with connector magento and maybe others.
What do you think?
@guewen

**Comment by pedrobaeza** [comment]
@sergio-teruel have you taken into account the new refactoring, isn't it?

**Comment by guewen** [comment]
@florian-dacosta  I didn't saw your comment before I'm working a lot on the new implementation these days. 
See https://github.com/OCA/connector/pull/231#issuecomment-308750369
Here you can it for the magento connector: https://github.com/guewen/connector-magento/tree/10.0-components.

I try to keep it compatible with `ConnectorUnit` and I think it will be. However, if you have to opportunity to base it on the new components, it'll be more extensible, and no further development will be done on the `ConnectorUnit` system.

It does not change so much, in fact. Changing from the `ConnectorUnit` to `Components` is rather fast as what changes is only the classes inheritance and the few attributes to declare (`_name`, `_usage`, `_apply_on`, ...) and replace the `unit_for` by `component` calls. It's easy for me though as the author, so you may struggle a bit more... I'm willing to write a small before/after guide in the next few days.

/cc @sergio-teruel @pedrobaeza

**Comment by sergio-teruel** [comment]
Thanks @guewen I will work in this migration based on your new magento work. 
cc @florian-dacosta

**Comment by pedrobaeza** [comment]
@guewen A migration guide would be definitively welcome, so that we can adapt this PR correctly.

**Comment by guewen** [comment]
For the record: http://connector-rework-doc.surge.sh/guides/migration_guide.html#migration-guide

**Comment by guewen** [comment]
One of the thing that could be improved by taking advantage of the new api, is the fact that a new client is opened for each connection to prestashop. I resolved it this way for magento: https://github.com/OCA/connector-magento/pull/255/commits/8d578f1f48c89cff57a306a8c3658be9fcfb1452

**Comment by atchuthan** [comment]
@sergio-teruel 
Let us know the base commits of the following repositories to test this PR.
queue: ?
connector: ?
connector_ecommerce: ?

**Comment by aierfino** [comment]
Hi,

We are interested in using this module shortly, can you please let me know when this pull request will be completed?

Thank you,

Adriana

**Comment by aierfino** [comment]
Hi @pedrobaeza, 

I commented two weeks ago on this PR and I have not gotten an answer. 

Is someone still working on this?

Thank you!

**Comment by pedrobaeza** [comment]
@aierfino have you tried this PR?

**Comment by aierfino** [comment]
Hi @sergio-teruel,

Can you let me know where you are at regarding this PR?

Thank you!

**Comment by sergio-teruel** [comment]
Hi @aierfino i did some basics changes to start import records, but we must basis the work as the same way that connector_magento with the new components... 
Any help are wellcome!!

**Comment by aierfino** [comment]
Hi @sergio-teruel, we will begin working on an Odoo projet shortly where we need to integrate prestashop. How can we help? How much work do you think still needs to be done? By when do you plan on finishing the migration? If you want we can plan a call to discuss. Thanks for your help.

**Comment by sergio-teruel** [comment]
Hi @aierfino Have you ever worked with connector_prestashop? If yes, you could help me to migrate to version 10. @guewen has already migrated connector_magento to v 10.. so we can take a look it...

**Comment by joserprieto** [comment]
@sergio-teruel, the PR is complete? 
Can it be tested with a real dev environment?
(PS 1.6.x and 1.7.x are avalaibles for test)

Regards.

**Comment by flotho** [comment]
Hi @sergio-teruel , Could it be tested ? Is the PR finished ?

**Comment by joserprieto** [comment]
@flotho i tested it on a dev environment, and not worked :cry:  

I tested it with Docker and the image provided by Tecnativa:

https://github.com/Tecnativa/docker-odoo-base

If you want to test, i put my configurations in pastebin:

./odoo/custom/src/repos.yaml:
https://pastebin.com/HwbU7d69

./odoo/custom/src/addons.yaml:
https://pastebin.com/fn4jxVxc

./odoo/custom/dependencies/apt_build.txt:
https://pastebin.com/Wv6Jvqip

/odoo/custom/dependencies/pip.txt:
https://pastebin.com/HC0qwRMw

Hope that helps you.

Regards.

**Comment by pedrobaeza** [comment]
We haven't finished this yet.

**Comment by flotho** [comment]
Is there anyway for me to contribute to your Repo?

**Comment by pedrobaeza** [comment]
Make a PR over our original branch to include your changes here

**Comment by flotho** [comment]
ok, thanks.
Any special parts you need some help ?

**Comment by joserprieto** [comment]
@bguillot, @sergio-teruel, the PR is complete?

Can it be tested with a real dev environment?

(I have PS 1.6.x and 1.7.x avalaibles for dev / testing purposes)

I'm testing right now a paid module, but if this PR is ready (althought is not still merged, and it can has any errors), i prefer to use the OCA module.

And report any errors that i encounter (it can be my mini little contribution, so sorry)

Regards.

**Comment by flotho** [comment]
Hi @joserprieto ,
From now, @pedrobaeza encouraged @bguillot and myself to propose a correct PR. Our efforts are there : https://github.com/akretion/connector-prestashop/pulls

From now, we succeed in getting base datas, order states , partners and sale order. Sadly some datas are not correctly matched and not all the partner etc... are imported, so we're working on it. Please have a look to the akretion PR that will be proposed as a PR into the repo of @Tecnativa , 

Hope it could help

**Comment by joserprieto** [comment]
Many thanks, @flotho 
I will try to test it this weekend (If my other projects do not eat me all the time, and me too, before ...)

**Comment by pedrobaeza** [comment]
I have cleaned commit history (it was hard to unscramble merge operations), and now there's a lot of lint errors and warnings, plus a missing test that errors the build:

https://travis-ci.org/OCA/connector-prestashop/builds/418570688?utm_source=github_status&utm_medium=notification

I have kept a copy of the original branch in https://github.com/Tecnativa/connector-prestashop/tree/10.0-mig-connector_prestashop-backup if you want to check the old commits.

@bguillot @flotho @FFernandez-PlanetaTIC any of you are going to greenify the branch?

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

@pedrobaeza, we are interested in migrate this module to v11.0 and will greenify this branch.

I remind you that OCA/product-attribute#359 migrates product_multi_image to v10.0 but it's still open. It allows to show imported images in product sheet.

Thanks!

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @pedrobaeza,

In bac2edafb9a4fa65a9f8a7f2cb7d804323665c39 you changed `AddressBatchImporter` from `prestashop.delayed.batch.importer` to `prestashop.direct.batch.importer`. There is some reason for this change? One of the tests fails for this reason.

Thanks!

**Comment by pedrobaeza** [comment]
It should be a side effect of the rebasing, which was devastating. Change it to the proper value and sorry for the inconveniences.

**Comment by FFernandez-PlanetaTIC** [comment]
No problem, I doubted if I has missed something, thanks.

**Comment by pedrobaeza** [comment]
@FFernandez-PlanetaTIC it seems this is still red in tests

**Comment by FFernandez-PlanetaTIC** [comment]
@pedrobaeza,

VCR isn't playing cassettes (recorded requests to a previous Prestashop) and consequently tests are trying to make new requests to a nonexistent Prestashop in http://localhost:8080

It works correcty in our environments, It seems to us an issue in Travis. Do these cassettes work properly in Travis for v9?

Thanks.

**Comment by pedrobaeza** [comment]
Tests are mocked because we can't have a real PrestaShop in Travis nor OCA. Have you changed the mocked methods for real ones?

**Comment by FFernandez-PlanetaTIC** [comment]
Maybe I haven't explained it well.

I've kept tests as they were: those who enqueue jobs are mocked and those who speak with Prestashop use VCR to simulate it.

I think the problem is that VCR does not work in Travis for v10.0:

https://travis-ci.org/OCA/connector-prestashop/jobs/429491839

> 2018-09-17 09:55:28,534 4770INFO openerp_test odoo.addons.connector_prestashop.tests.test_auth: test_auth_success (odoo.addons.connector_prestashop.tests.test_auth.TestAuth)
> 2018-09-17 09:55:29,547 4770ERROR openerp_test odoo.addons.connector_prestashop.tests.test_auth: ` UserError: (u"Connection failed\n\nAPI / Network Error:\n\nHTTPConnectionPool(**host='localhost', port=8080**): Max retries exceeded with url: **/api/** (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc2a0cca6d0>: Failed to establish a new connection: [Errno 111] **Connection refused**',))", '')

However it does for v9.0:

https://travis-ci.org/OCA/connector-prestashop/jobs/280853246
> 2017-09-28 12:58:38,677 5451INFO openerp_test openerp.addons.connector_prestashop.tests.test_auth: test_auth_success (openerp.addons.connector_prestashop.tests.test_auth.TestAuth)
> 2017-09-28 12:58:38,699 5451INFO openerp_test **vcr.stubs**: **Playing response for <Request (HEAD) http://localhost:8080/api/> from cassette**

Someone knows what can occur?

Thanks!

**Comment by pedrobaeza** [comment]
Sorry, the fault is mine as I didn't know the internals of tests (they were develop by C2C) and then didn't catch the joke about the cassettes. There shouldn't be any difference between 9.0 and 10.0, as both run Python 2.7 and pip dependencies are the same.

@guewen do you have any clue about the connection error on these tests?

**Comment by flotho** [comment]
Hi @FFernandez-PlanetaTIC , @pedrobaeza 

@bguillot and I initiated a huge worked here https://github.com/akretion/connector-prestashop/tree/10.0-mig-connector-prestashop-ak followed by other partners.
All the usual workflows have been tested correctly by one or more contributors.
Don't we have some duplicate work here ? 
@bguillot , maybe it's time for you to propose the PR to OCA.

Regards

**Comment by pedrobaeza** [comment]
@flotho why don't you say so in that moment? We have been talking about this a lot of time, and I even told you of superseeding my branch, but you didn't do it. Now a lot of time has been wasted. Then please propose that branch here, but:

1. Include PlanetaTIC and @FFernandez-PlanetaTIC as contributor, as they deserve that position
2. Make sure all the CIs are correct, and if not, make them happy. You can check this branch for some of the cleanup/fixes.
3. Do it ASAP, for finally converging and finish this work.

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

@pedrobaeza , I think it hasn't been lost so much effort. To bring some light:

1. @sergio-teruel started here
2. @bguillot and @flotho did an awesome work in https://github.com/akretion/connector-prestashop/tree/10.0-mig-connector-prestashop-ak
3. My fixes (akretion/connector-prestashop#4) and @florian-dacosta improvement (akretion/connector-prestashop#5) were merged to Akretion branch
4. Akretion branch was merged here with Tecnativa/connector-prestashop#6
5. I tried to greenify this with Tecnativa/connector-prestashop#9
6. The only thing that's missing here are 2 commits / 3 files changed by @flotho in akretion/connector-prestashop#6

Please, @flotho , can you follow Pedro's advice and propose here your work in akretion/connector-prestashop#6

Let's try to close this topic soon :checkered_flag:

Excuse me if some collaborator is missing :pray:

Thanks to all!

**Comment by pedrobaeza** [comment]
@FFernandez-PlanetaTIC that's a relief to know that only 2-3 commits are missing in this PR from that branch. We still have the problem with VCR. Nobody know what's happening?

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

About the problem with VCR, it worked in the last merged PR #85 :

https://travis-ci.org/OCA/connector-prestashop/jobs/280853246#L1531

```
2017-09-28 12:58:38,677 5451 INFO openerp_test openerp.addons.connector_prestashop.tests.test_auth: test_auth_success (openerp.addons.connector_prestashop.tests.test_auth.TestAuth)
2017-09-28 12:58:38,699 5451 INFO openerp_test vcr.stubs: Playing response for <Request (HEAD) http://localhost:8080/api/> from cassette 
```

But it has stopped playing in the last open PR #95 :

https://travis-ci.org/OCA/connector-prestashop/jobs/431445949#L1421

```
2018-09-21 11:35:13,425 22176 INFO openerp_test openerp.addons.connector_prestashop.tests.test_auth: test_auth_success (openerp.addons.connector_prestashop.tests.test_auth.TestAuth)
2018-09-21 11:35:13,448 22176 INFO openerp_test requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-09-21 11:35:13,450 22176 ERROR openerp_test openerp.addons.connector_prestashop.tests.test_auth: FAIL
```

Both are v9.0 an the only difference is b699a24d51ee2cf9aa16f637082ea8ae6b538961 . I don't know if the preceding commit is the reason why VCR stops playing. Or it has been a change in Travis configuration.

Any ideas?
Thanks!

**Comment by pedrobaeza** [comment]
@FFernandez-PlanetaTIC the problem is the version of vcrpy, that has breaking changes. I have frozen that version and now Travis is green, and have also update .travis.yml file for having also runbot working, and remove the required flag on one field in account.tax.group (that it's a bit weird to be in this module, but hey, I'm not going to put more objections).

I merge this, and if there's something more (as the mentioned 3/4 commits ahead in the other branch), please make another PR.

Congratulations to all for this great milestone!

**Pull request merged**
