### PR TITLE
[15.0][MIG] connector_prestashop

### PR DESCRIPTION
**Pull request by flachica**
Dependency below, please review

https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector/pull/428
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

### CODE REVIEW

**Comment by jacekmichalski** [comment]
Any news when can we expect the merge?

**Comment by leemannd** [comment]
Hello @jacekmichalski it needs to be reviewed and approved before it could be merged. Your review is welcome

**Comment by flachica** [comment]
@jacekmichalski In order to accept this migration, it is also necessary to review this list of PR's

https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

**Comment by Neitherkx** [comment]
Hello, I needed to use this module for v15 and I see that this PR is not working. I had planned to make a supersed to fix the problems and be able to merge.

**Pull request closed without merging**
