### PR TITLE
Migration To Odoo 8.0

### PR DESCRIPTION
**Pull request by parthivgls**
Migration To Prestashop 8.0 with changes for Product, Sale Order , Tax, Tax Rules and Configuration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this a migration started from scratch different from https://github.com/OCA/connector-prestashop/pull/11?

**Comment by parthivgls** [comment]
@pedrobaeza : it has some parts taken from #11 into the code as well..

**Comment by pedrobaeza** [comment]
Yeah, but you haven't respect then the authorship. You should use my initial branch, and then change whatever you want.

**Comment by parthivgls** [comment]
@pedrobaeza : I'll be more than happy to comply, what's the best way to do that.

**Comment by pedrobaeza** [comment]
Try to rebase your branch from the branch of my PR, and then force push to your one.

**Comment by flotho** [comment]
Hi @parthivgls could you precise which version of :
- OCA connector you used
- Prestapyt
- product-attribute

**Comment by flotho** [comment]
Hi  @parthivgls ,
I tried to install your connector and it failed on product images. Are you using the old 7.0 branch of product attribute?
Additionally, could you explain why you remove product_multi_image dependency and replace with nothing equivalent?

**Comment by flotho** [comment]
Hi @parthivgls 
I tried to run synchronize_basedata and I have an error in import_batch(session, 'prestashop.configuration', backend_id) line 140.
The error is the following :

```
2015-09-29 17:15:21,212 333 DEBUG ysee-techreceptive openerp.addons.connector.unit.mapper: converting record {'date_add': '2012-06-11 14:24:48', 'name': 'PS_LANG_DEFAULT', 'date_upd': '2012-06-11 14:26:40', 'id_shop': '', 'id': '1', 'value': '2', 'id_shop_group': ''} to model prestashop.configuration()
2015-09-29 17:15:21,215 333 WARNING ysee-techreceptive openerp.addons.prestashoperpconnect.unit.mapper: Deprecated: backend_id at line 869: 'Session(...).search(...)' has been deprecated in favor of 'Session(...).env['model'].search(...)'
2015-09-29 17:15:21,221 333 WARNING ysee-techreceptive openerp.addons.prestashoperpconnect.unit.mapper: Deprecated: backend_id at line 871: renamed to binder_for()
2015-09-29 17:15:21,229 333 WARNING ysee-techreceptive openerp.addons.prestashoperpconnect.unit.mapper: Deprecated: backend_id at line 879: 'Session(...).search(...)' has been deprecated in favor of 'Session(...).env['model'].search(...)'
2015-09-29 17:15:21,232 333 WARNING ysee-techreceptive openerp.addons.prestashoperpconnect.unit.mapper: Deprecated: backend_id at line 896: 'Session(...).create(...)' has been deprecated in favor of 'Session(...).env['model'].create(...)'
2015-09-29 17:15:21,240 333 ERROR ysee-techreceptive openerp.sql_db: bad query: INSERT INTO "product_pricelist" ("id", "active", "currency_id", "type", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('product_pricelist_id_seq'), true, NULL, 'sale', 'Sale Pricelist', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « currency_id »
DÉTAIL : La ligne en échec contient (8, 1, 2015-09-29 17:14:20.114077, Sale Pricelist, null, 1, null, 2015-09-29 17:14:20.114077, t, sale)

2015-09-29 17:15:21,244 333 DEBUG ysee-techreceptive openerp.service.model: IntegrityError
.../...
IntegrityError: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « currency_id »
DÉTAIL : La ligne en échec contient (8, 1, 2015-09-29 17:14:20.114077, Sale Pricelist, null, 1, null, 2015-09-29 17:14:20.114077, t, sale)
```

Corrected with https://github.com/techreceptives/connector-prestashop/pull/1

**Comment by flotho** [comment]
Hi @parthivgls 
There is a problem on categories with multiple languages.
```
  File "/home/florent/DEV/Projets_Ezytail/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/binder.py", line 93, in to_openerp
    assert len(bindings) == 1, "Several records found: %s" % (bindings,)
AssertionError: Several records found: prestashop.product.category(4, 5, 6)
```

**Comment by flotho** [comment]
Hi @parthivgls another test failure.
While trying to import partners, I have this messages :

```
Traceback (most recent call last):
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/controllers/main.py", line 81, in runjob
    job.perform(session)
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/job.py", line 467, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/home/florent/DEV/Projets/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/import_synchronizer.py", line 1023, in import_customers_since
    session, 'prestashop.res.partner', backend_id, filters, priority=15
  File "/home/florent/DEV/Projets/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/import_synchronizer.py", line 990, in import_batch
    importer.run(filters=filters, **kwargs)
  File "/home/florent/DEV/Projets/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/import_synchronizer.py", line 181, in run
    record_ids = self._run_page(filters, **kwargs)
  File "/home/florent/DEV/Projets/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/import_synchronizer.py", line 187, in _run_page
    self._import_record(record_id, **kwargs)
  File "/home/florent/DEV/Projets/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/import_synchronizer.py", line 291, in _import_record
.../...
Exception: CPU time limit exceeded.
```

In the log there are some recurrent messages :

```
 openerp.tools.translate: translation went wrong for "'%s created'", skipped
```

Working with a a date in the partner import limits those message and then it works.

FIX : adapt proper options tanks to https://www.odoo.com/fr_FR/forum/help-1/question/difference-between-built-in-multiprocessor-mode-and-gunicorn-1671

**Comment by parthivgls** [comment]
@flotho : yes for product_images I need review from @pedrobaeza about what to do ? whether to migrate old module or replace with something else.

**Comment by flotho** [comment]
@parthivgls , this is really strange because you already had 3226992 in your branch and this commit deals with multipe images.
Won't it be possible to reuse the images part of this one? Would you like me to do this for you?

**Comment by parthivgls** [comment]
@flotho : yes please.

**Comment by pedrobaeza** [comment]
@parthivgls, you should use the new product_multi_image module (it was already adapted previously in my branch).

**Comment by flotho** [comment]
@parthivgls, @pedrobaeza I'll deal with product multi image and will deliver in about 12 hours.

**Comment by flotho** [comment]
@parthivgls, @pedrobaeza , I have addtionnal questions
I can't figure out what is the logic behind the active product :
- https://github.com/OCA/connector-prestashop/pull/16/files#diff-389abd144575ecda5c825c2b48379410R240 always_available, what is this? An inactive product on PS still active on Odoo!
- regarding the product type, https://github.com/OCA/connector-prestashop/pull/16/files#diff-389abd144575ecda5c825c2b48379410R335 what could be the condition to have [consu] products? Some of my products are not set as [stockable]

Thanks

**Comment by flotho** [comment]
@parthivgls,

I pushed a PR for you :https://github.com/techreceptives/connector-prestashop/pull/2
Hope it helps

**Comment by flotho** [comment]
@pedrobaeza could you explain me the strategy regarding product.product
Do we have to replace combination by this one? Or is it the opposite?

**Comment by pedrobaeza** [comment]
As far as I remember, combination = product.product, and prestashop product = product.template.

**Comment by flotho** [comment]
@pedrobaeza thanks.
Another great  question. I pushed some improvements on products prices : https://github.com/flotho/connector-prestashop/commit/4be32a0aabdd83d839be3d39e6991f86a1148002
regarding the extra price in odoo, I think it won't be possible to "map" it to PS prices. In PS1.5, the effects are added while you are generating combinations so that teh impact price is already the result of many effects of the attributes.
Do you share this point of view? Any workaround?

regards

**Comment by pedrobaeza** [comment]
Yeah, there's a problem with that, because Prestashop put an specific price for each combination and Odoo works with extra prices per attribute. We included an heuristics to try to deduce that extra prices comparing combination prices with their attributes:
- If a combination has the same price as the product, then all attributes that compound that combination doesn't have any extra price.
- If another combination has a different price, the attribute subset shared with the previous combination can be deducted that will have extra price 0, and the remaining attributes are those that rises the price.

Anyway, there are chances to end with an incorrect combination/combination price set that doesn't allow the conversion.

**Comment by flotho** [comment]
@pedrobaeza , sad news there

**Comment by flotho** [comment]
@pedrobaeza , the file architecture is really a pity.
Could you explain me the purpose of having mapping classes in mapper.py and other in other files?
Is it an historical consequence? What is the good way to work from now?

**Comment by pedrobaeza** [comment]
The reason is probably for historical reason and the lack of budget, which makes this a very accidental migration. I wasn't very involved with this work due to my overload and couldn't control these things.

**Comment by guewen** [comment]
Apparently, it only works with the version 2.2.0 of OCA/connector. Could you confirm?

**Comment by pedrobaeza** [comment]
Yeah, that's it. We never got enough budget for the switch.

**Comment by guewen** [comment]
> Yeah, that's it. We never got enough budget for the switch.

Not a criticism, just wanted to be sure of that and for the record, because many people try to install it and have failures due to that so it ought to be mentioned.

**Comment by pedrobaeza** [comment]
No problem. I was also just clearing. @parthivgls can also say if it's in their plans to switch to the newest version.

**Comment by parthivgls** [comment]
Plans ??  ... It's in progress .. :)

On Wed, Nov 25, 2015 at 1:34 PM, Pedro M. Baeza notifications@github.com
wrote:

> No problem. I was also just clearing. @parthivgls
> https://github.com/parthivgls can also say if it's in their plans to
> switch to the newest version.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/connector-prestashop/pull/16#issuecomment-159529254
> .

## 

Thanks & Regards,
Parthiv Patel

**Comment by gurneyalex** [comment]
@sebastienbeau @arthru as members of this PSC, your reviews are welcome

**Comment by pedrobaeza** [comment]
We are proposing on Wednesday a totally new PR, so I close this one.

**Pull request closed without merging**
