### PR TITLE
[10.0] [FIX] connector_prestashop: Fix resync

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**
Hi,

This fixes resync error:

resync

```
  File "/.../connector_prestashop/models/binding/common.py", line 88, in resync
    record.prestashop_id)
TypeError: import_record() takes no arguments (4 given)
```

Regards!

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Waiting for Travis green

**Comment by FFernandez-PlanetaTIC** [comment]
@MPoch-PlanetaTIC has already sent the signed CLA to cla AT odoo-community.org @oca-clabot

**Review by flotho — APPROVED** [review]
looks good to me

**Comment by pedrobaeza** [comment]
OK, let's merge this, but please investigate the problem.

**Pull request merged**
