### PR TITLE
[10.0][MIG]Add rest of Akretion modifications

### PR DESCRIPTION
**Pull request by flotho**
Some part of PR haven't been pushed to Akretion before OCA merge @bguillot  PR.
This PR propose to re-add all missing parts

### CODE REVIEW

**Comment by flotho** [comment]
Replace :
* https://github.com/OCA/connector-prestashop/pull/100
* https://github.com/akretion/connector-prestashop/pull/7

**Comment by pedrobaeza** [comment]
Can you check Travis?

**Comment by gaelTorrecillas** [comment]
hello @oca-clabot, 
I upgraded my account.

Regards,

**Comment by pedrobaeza** [comment]
Travis is still red. Can you please check?

**Comment by flotho** [comment]
Hi @pedrobaeza , are we almost there?
Are the tests failure normal regarding to you ?

regards

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @flotho ,

We have the same test failure in #103 and we are reviewing it.

Regards!

**Comment by FFernandez-PlanetaTIC** [comment]
Hello again,

Our #104 is also affected by the test failure.

We don't get this error in our environments and I don't understand why... :confused: 

I think it's related to #77 , which should have been fixed with #81 .

Regards

**Comment by flotho** [comment]
Hi @FFernandez-PlanetaTIC , it's also failing randomly in our tests.
@pedrobaeza any chance to have a positive review for a merge or do we have to also deal with this issue?
regards

**Comment by pedrobaeza** [comment]
The idea of tests is to have predictable results, so it's weird that this happens randomly. There should be a cause. Isn't possible to debug what is the underlying problem and fix it?

**Comment by flotho** [comment]
Hi @pedrobaeza , of course it should be possible.
Yet either @FFernandez-PlanetaTIC and our team have some difficulties to reproduce.
Moreover, many proposal for v10 are in the pipe.
I'm not sure we'll be able to find what's happening soon. @FFernandez-PlanetaTIC , what's your point of view?

**Comment by FFernandez-PlanetaTIC** [comment]
I have debugged the failing test on friday and today but it doesn't fail in our environments and I can't find the cause :confused:

Maybe @simahawk and @nbessi can give us a clue as it seems that they had the same problem in #77 and #81 .

**Comment by FFernandez-PlanetaTIC** [comment]
Finally we reproduced and fixed it in #104 

Damn cache! :rage:

**Comment by pedrobaeza** [comment]
@FFernandez-PlanetaTIC 2 things about this:

* Please do a separate PR for fixing Travis (and possibly fast-tracking).
* About the solution, this is revealing a bad `depends` declaration on any of the fields that you are handling. This fixes tests, but probably in real world you would face the same problem. Can you dig a bit more which field contains the incorrect value and then deduce the dependent fields that are not declared?

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @pedrobaeza ,

I think it's a problem in _stock_ module, a quick test:

```
paco@coloma$ bin/python_odoo 
To start the Odoo working session, just do:
    session.open(db=DATABASE_NAME)
or, to use the database from the buildout part config:
    session.open()
All other options from buildout part config do apply.
Then you can issue commands such as:
    session.registry('res.users').browse(session.cr, 1, 1)
Or using new api:
    session.env['res.users'].browse(1)

>>> session.open('test_10.0_catalog_manager')
2018-12-18 10:08:59,791 20350 INFO test_10.0_catalog_manager odoo.modules.loading: loading 1 modules...
2018-12-18 10:08:59,862 20350 INFO test_10.0_catalog_manager odoo.modules.loading: 1 modules loaded in 0.07s, 0 queries
2018-12-18 10:08:59,898 20350 INFO test_10.0_catalog_manager odoo.modules.loading: loading 64 modules...
2018-12-18 10:09:00,003 20350 INFO test_10.0_catalog_manager odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-12-18 10:09:00,295 20350 INFO test_10.0_catalog_manager odoo.modules.loading: 64 modules loaded in 0.40s, 0 queries
2018-12-18 10:09:00,772 20350 INFO test_10.0_catalog_manager odoo.modules.loading: Modules loaded.
>>> 
>>> product = session.env['product.product'].create({'name': 'Test'})
>>> product.qty_available
0.0
>>> product.product_tmpl_id.qty_available
0.0
>>> 
>>> warehouse = session.env['stock.warehouse'].search([], limit=1)
>>> 
>>> qty_change = session.env['stock.change.product.qty'].create({'location_id': warehouse.lot_stock_id.id, 'product_id': product.id, 'new_quantity': 10})
>>> qty_change.change_product_qty()
{'type': 'ir.actions.act_window_close'}
>>> 
>>> product.qty_available
10.0
>>> product.product_tmpl_id.qty_available
0.0
>>> 
>>> session.env.invalidate_all()
>>> product.product_tmpl_id.qty_available
10.0
```

What do you think? Should we create an issue in odoo/odoo or OCA/OCB?

Thanks!

**Comment by pedrobaeza** [comment]
Thanks for the insights, @FFernandez-PlanetaTIC. That has been very helpful!

Indeed, there's a problem in Odoo code. Look the compute method of `product.product`.`qty_available` field:

https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L100-L101

It has their corresponding depending fields for properly recomputing things when one of the values change.

But for `product.template`, what we have is:

https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L434-L435

without `@api.depends`, and this is what is causing the glitch. If the value hasn't been accessed previously, then it computes the right value when needed, but on contrary if it has been computed previously, then accessing again when conditions have changed will show the incorrect value.

This should be fixed at Odoo/OCB level. The solution should be - without testing further - to add these depends on the `product.template` field:

```python
@api.depends(
    'product_variant_ids',
    'product_variant_ids.stock_quant_ids',
    'product_variant_ids.stock_move_ids',
)
def _compute_quantities(self):
    ...
```

It would be great if you try to put this in Odoo (directly a PR), with the same shell console commands for illustrating the problem, and with this solution. I will ping proper people for reviewing it and hopefully to get merged. If not, we can go to OCB, but we have to check if this is also happening on v11/v12 for giving this more importance to be pushed in core.

Finally, you don't have to wait all of this for solving the problem without invalidating the cache in this module, as this only hides the problem in the tests, but in the real world can happen. This is the great thing about modularity! Just add an inherit to `product.template` with the following:
```python
class ProductTemplate(models.Model):
    _inherit = 'product.template'

    @api.depends(
        'product_variant_ids',
        'product_variant_ids.stock_quant_ids',
        'product_variant_ids.stock_move_ids',
    )
    def _compute_quantities(self):
        return super(ProductTemplate, self)._compute_quantities()
```
with this, you are adding the dependencies and achieving the same result. However, put a comment on this code for noting that this is patch until PR X gets merged in Odoo.

**Comment by FFernandez-PlanetaTIC** [comment]
We have already created/modified the PRs as suggested:

- odoo/odoo#30024
- odoo/odoo#30026
- #106

**Pull request closed without merging**
