### PR TITLE
7.0 improved and fixed

### PR DESCRIPTION
**Pull request by florian-dacosta**
The version 7.0 of connector-prestashop is not compatible with connector e-commerce branch anymore. And there are a lot of other issues.
The goal of this PR is to improve it and make it somehow usable, but it does not fix eveything.

### CODE REVIEW

**Comment by atchuthan** [comment]
@florian-dacosta: may I know the status of this PR?
Also, it would be helpful for others if you have the key points/bulletins to add the points that are done and to do too.

**Comment by florian-dacosta** [comment]
@atchuthan 
This Pr is waiting reviews I guess.
It fixes the 7.0 branch so it works with the last version of the connector.
It is used in production for 1 customer, so far so good
But this is a simple case customer.

**Comment by atchuthan** [comment]
@florian-dacosta thanks... I will take a look at it.

@pedrobaeza Label change to "Needs review"

**Comment by pedrobaeza** [comment]
If you can fix CIs status, we can consider merging. If not, we should close it as there's not too much interest in this old version.

**Comment by rafaelbn** [comment]
Dear @florian-dacosta , this PR has 1 year old, are you going to fix CIs status? Thanks

**Comment by florian-dacosta** [comment]
It is not in my priorities. I guess, as Pedro said, there is not too much interest to merge it for version 7.0.
I close it.

**Comment by pedrobaeza** [comment]
Note that I merged tonight version 8, which is working for use for more than a year, and today I want to merge version 9.

**Pull request closed without merging**
