### PR TITLE
[10.0] [FIX] connector_prestashop: employee access rights

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**
Add employee access rights to avoid errors like this on register payment in invoices:

image

cc @PlanetaTIC

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Correct patch is to add proper groups on the views that add this field.

**Comment by FFernandez-PlanetaTIC** [comment]
No view in `connector_prestashop` adds fields in register payment wizard.

`default_get` of register payment reads all fields of the invoice, PrestaShop bindings included, triggering the previous error.

We have granted to employees read access for remaining PrestaShop bindings.

**Comment by pedrobaeza** [comment]
Really? Something is triggering that permission error, but it's not the default. Please dig a bit more.

**Comment by FFernandez-PlanetaTIC** [comment]
```
"Traceback (most recent call last):
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/addons/account/models/account_payment.py", line 272, in default_get
    invoice_defaults = self.resolve_2many_commands('invoice_ids', rec.get('invoice_ids'))
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 4681, in resolve_2many_commands
    for data in records.read(fields):
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 3017, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 3167, in _read_from_database
    field.read(fetched)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/fields.py", line 2205, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 4244, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/models.py", line 3292, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-4>", line 2, in check
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo10/palmatrend/parts/OCA/OCB/odoo/addons/base/ir/ir_model.py", line 950, in check
    raise AccessError(msg % msg_params)
AccessError: (u'Lo siento, no tiene permiso para acceder a este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Connector/Connector Manager\n\n(Modelo de documento: prestashop.refund)', None)
```

**Comment by pedrobaeza** [comment]
What I see there is that the field is populated when resolving that `invoice_ids`, but you have to go upper in the chain, where the other field is populated or fetched. You can even put a `groups` at field level.

**Comment by FFernandez-PlanetaTIC** [comment]
```
"Traceback (most recent call last):
  File "../OCA/OCB/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "../OCA/OCB/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "../OCA/OCB/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "../OCA/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "../OCA/OCB/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "../OCA/OCB/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "../OCA/OCB/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "../OCA/OCB/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "../OCA/OCB/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "../OCA/OCB/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "../OCA/OCB/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "../OCA/OCB/addons/account/models/account_payment.py", line 272, in default_get
    invoice_defaults = self.resolve_2many_commands('invoice_ids', rec.get('invoice_ids'))
  File "../OCA/OCB/odoo/models.py", line 4681, in resolve_2many_commands
    for data in records.read(fields):
  File "../OCA/OCB/odoo/models.py", line 3017, in read
    self._read_from_database(stored, inherited)
  File "../OCA/OCB/odoo/models.py", line 3167, in _read_from_database
    field.read(fetched)
  File "../OCA/OCB/odoo/fields.py", line 2205, in read
    lines = comodel.search(domain, limit=self.limit)
  File "../OCA/OCB/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "../OCA/OCB/odoo/models.py", line 4244, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "../OCA/OCB/odoo/models.py", line 3292, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-4>", line 2, in check
  File "../OCA/OCB/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "../OCA/OCB/odoo/addons/base/ir/ir_model.py", line 950, in check
    raise AccessError(msg % msg_params)
AccessError: (u'Lo siento, no tiene permiso para acceder a este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Connector/Connector Manager\n\n(Modelo de documento: prestashop.refund)', None)
"
```

**Comment by FFernandez-PlanetaTIC** [comment]
There's no need to reinvent the wheel.

Read access for PrestaShop bindings is already being granted to employees:

https://github.com/OCA/connector-prestashop/blob/10.0/connector_prestashop/security/ir.model.access.csv

We only add them to the remaining bindings.

**Comment by pedrobaeza** [comment]
For me that's an information disclosure as an easy exit (so I'm saying that previous similar actions) are also bad done, but of course works. If others consider this as a good solution, go ahead.

**Pull request closed without merging**
