### PR TITLE
[WIP] [MIG] Migrated Prestashop connector to v8

### PR DESCRIPTION
**Pull request by pedrobaeza**
This is the work in progress of the Prestashop connector for v8.

It depends on:
- [ ] https://github.com/OCA/product-attribute/pull/57
- [x] https://github.com/OCA/e-commerce/pull/35
- [x] https://github.com/OCA/connector-ecommerce/pull/18

### CODE REVIEW

**Comment by guewen** [comment]
Hi @pedrobaeza 

You must be aware of OCA/connector#47 which changes a bit the connector's API. I think you already are as you mention the dependency on OCA/connector-ecommerce#18 but just in case it is worth to mention it.

**Comment by pedrobaeza** [comment]
Thanks for mentioning. As we started this work at the very beginning, probably there will be things to adjust. For now, I have been working with freeze versions. I will update each dependency when I finish of other tasks.

First of all, product_images, which I have totally redone. This is also used on Magento connector, right? Please check then what I'm doing on https://github.com/OCA/product-attribute/pull/57

**Comment by guewen** [comment]
> First of all, product_images, which I have totally redone. This is also used on Magento connector, right? Please check then what I'm doing on OCA/product-attribute#57

It was used in version < 7.0, till 7.0 it is not used anymore. Thanks for mentioning though.

**Comment by pedrobaeza** [comment]
Ahm, curious. And now how you handle multiple images?

**Comment by guewen** [comment]
@pedrobaeza Previously the products were created on Odoo and exported to Magento, now the products are created on Magento and imported into Odoo. Magento needs a lot of marketing and presentation data while Odoo needs basic information. We only import the main image.

**Comment by pedrobaeza** [comment]
Ah, OK. Then sooner or later you will need it, because a target of a lot of companies is to manage full information from the ERP. I have done it partially with the possibility to export products on _prestashoperpconnect_catalog_manager_.

**Comment by guewen** [comment]
Perhaps. 
Akretion worked on that for the Magento Connector but as far as I know it is not ready yet, so that's indeed possible they used it.

On a side note, I prefer to try explain why it is a bad idea to manage the full information in the ERP (which is not possible anyway, but that's maybe only because the other side is Magento) than to work on thousands of lines of code to have a half-baked catalog export. Here is an email I wrote one year ago: https://gist.github.com/guewen/40c96c26ee2911d3da90

**Comment by pedrobaeza** [comment]
As you say, Odoo it's not a full PIM, but two things forces to go to close to this:
- E-commerce integrated in Odoo is going to make that Odoo/community integrates more of this on base system.
- A lot of customers (including the one that finances part of this migration) wants to manage a subset (as it is difficult to have the full set) of the catalog properties in Odoo, not in Magento/Prestashop.

**Comment by kintaro1981** [comment]
I think that if "full management" make too difficult upgrade to future versions then subset management is fine. But it has to be clear documented "what yes and what no".

Then if time and new development will bring "full management", well... thank you! :+1:

**Comment by pedrobaeza** [comment]
I have pushed last changes to the branch, but there's still no compatibility with 3.0 version of the connector, but there's no too much work to do.

I haven't also switched the module _product_images_ in favor of _product_multi_image_, so you can still use the v7 one.

**Comment by bguillot** [comment]
Hi,

FYI, I started to ensure the compatibility with connector v 3.0 based on @pedrobaeza's work. 

I will make a PR with my fixes and improvements on his branch, it will update this PR.

**Comment by flotho** [comment]
Hi all of you,
How could I collaborate on this project too? It seems that there are many branches from many of you. What is the best way for me to push some code?
Regards

**Comment by flotho** [comment]
Hi, 
I'll sign the CLA today

**Comment by flotho** [comment]
Hi @pedrobaeza 

I tried your with the following configuration :
- Latest Odoo 8.0 pulled
- I use OCA connector 3.1.0, maybe @bguillot could make the PR for this part? Do I have to test wth a precedent release of the connector?
- I use your repo for product-attribute and use the product_multi_image module you rewrote and change the dependencies in the manifest
  - I also rename the product.images into product.image , this PR will be merged once https://github.com/OCA/product-attribute/pull/57 will be merged
- I use the OCA latest e-commerce and connector e-commerce as the needed PR has already been merged

With all this stuff I succeed in installing and configuring the backend, when I try to import base datas it looks that something is running (many logs connecting to the server etc...), yet it doesn't import anything. 
Anyone advice would be appreciated.
regards

**Comment by flotho** [comment]
Hi @pedrobaeza 

When I try to run the first import of the PS datas, I have this message :

```
  File "/home/florent/DEV/Lib_Odoo/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/binder.py", line 86, in to_openerp
    context=self.session.context
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
TypeError: search() got multiple values for keyword argument 'limit'
```

I don't find multiple limit keyword, only one is present. Could it come form the version of the connector?

**Comment by pedrobaeza** [comment]
This works currently with the previous version of the connector, not the current one.

**Comment by flotho** [comment]
Hi @bguillot 
Any chance to see/help the content of your modifcation so that the latest connector works with this PR?

**Comment by flotho** [comment]
Hi @pedrobaeza 

could you give me the commit you use, is it the V7 one, or the v8 one with an older tag?
Thanks

**Comment by flotho** [comment]
Hi all,

As the pR is based on an outdated OCA connector, I propose to merge this PR in a specific branch different from 8.0 and/or add a tag to precise this.
What do you think about this?
Regards

**Comment by pedrobaeza** [comment]
But both works on 8.0, so the branch is not incorrect at all. You only need to work with a previous tag of the 8.0 connector branch.

**Comment by flotho** [comment]
Thanks for your answer @pedrobaeza,  which tag do you use? the 2.2.0 or the 3.0.0 ?

**Comment by pedrobaeza** [comment]
2.2.0

**Comment by flotho** [comment]
Thanks @pedrobaeza , does the 2.2.0 also implements the jobrunner http://odoo-connector.com/guides/jobrunner.html and does the conf has to be the same with env variable to export?

**Comment by pedrobaeza** [comment]
No, that was one of the things added in last connector version and what makes not to work current code with it.

**Comment by flotho** [comment]
ok, so we still on worker process, so the official ressource to follow is this one : http://odoo-connector.com/guides/multiprocessing.html am I correct?

**Comment by pedrobaeza** [comment]
I think so, but I'm not the developer of the connector part, so I'm not sure.

**Comment by flotho** [comment]
@pedrobaeza isn't the way you deploy it and make it work?

**Comment by pedrobaeza** [comment]
Well, workers is a general feature of Odoo that I always put in deployed servers, but I don't know its bind with connector part.

**Comment by flotho** [comment]
well I wasn't really focused on the worker aspect but much more on the way you run odoo to make the connector work?
Is there a special conf you use for running your 2.2.0 connector tag? Does the simple fact to declare it in the conf file is enough? do you add special options in the command (except workers > 0 of course)

**Comment by pedrobaeza** [comment]
No, I don't. Standard config with workers and nothing more.

**Comment by flotho** [comment]
@pedrobaeza , great thanks, I'll try this asap

**Comment by flotho** [comment]
When trynig this :
- Connector OCA 2.2.0 tag
- This repo on your PR
- Workers = 3
- no additionnal env conf

I have this error

```
from openerp.osv.osv import PG_CONCURRENCY_ERRORS_TO_RETRY
ImportError: cannot import name PG_CONCURRENCY_ERRORS_TO_RETRY
```

Any chance to have a tip for me?
regards

**Comment by flotho** [comment]
Ok, this part solved by modifing the import in the 2.2.0 tag by :

```
from openerp.service.model import PG_CONCURRENCY_ERRORS_TO_RETRY
```

**Comment by flotho** [comment]
Pfiouuuu, I finished to find a commit working.
This one d381118 and is tagged as 3.0 and not 2.2.0 ;-)
Regards

**Comment by flotho** [comment]
Hi @pedrobaeza, 
I have a problem while parsing images

```
  File "/home/florent/DEV/Lib_Odoo/gitMag-connector-prestashop-pedrobaeza/prestashoperpconnect/unit/backend_adapter.py", line 51, in get_image
    if response.content:
AttributeError: 'tuple' object has no attribute 'content'
```

I checked that the full_url is parseable and it is, the image exists, do you already had this issue?
regards

**Comment by pedrobaeza** [comment]
@flotho, please wait until my partner @mikelarre come back from holidays to answer these questions.

**Comment by flotho** [comment]
@pedrobaeza thanks for your answer, I'll try to find this by myself until @mikelarre come back from holidays

**Comment by flotho** [comment]
@pedrobaeza foudn, the version of request wasn't correct. using the 0.14 instead of the official 2.x make it works now

**Comment by flotho** [comment]
Hi @pedrobaeza , This PR seems to be able to pass if this one could https://github.com/OCA/product-attribute/pull/57
Any chance to find out what's the mess with MRP datas in this PR

**Comment by cubells** [comment]
I have a customer that needs that module.

May I help on that?
what is the current status?

**Comment by pedrobaeza** [comment]
We are working on this again. Financial help is always welcome to complete features.

**Comment by Moret84** [comment]
Hello, 
I am interested in the V8 version of the module. Just out of curiosity, what are the blocking points and the current status of the project ? Did the module V7 version work ? What make so hard to migrate from V7 to V8 (not a criticism at all, I am also a developer and I just want to understand to know if I could help) ?

**Comment by jesusVMayor** [comment]
@pedrobaeza, I am also interested in this migration. What is the state? How i can help?

**Comment by flotho** [comment]
Hi @Moret84 , Hi @jesusVMayor ,

FYI, I've spent a lot of time on this https://github.com/flotho/connector-prestashop/tree/8.0_connector-prestashop_mig
There was a lot of developments and improvements but I hadn't time to make it "OCA certified"

It works perfectly for our integrations.

regards

**Comment by pedrobaeza** [comment]
Superseeded by #22

**Pull request closed without merging**
