### PR TITLE
[IMP] Add version and conversion keys for prestashop 1.6.1.11

### PR DESCRIPTION
**Pull request by hugosantosred**
Prestashop Api has changed some keys for version 1.6.1.11

This PR is intended to make the connector compatible with the API conversion keys of this version.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I'm too tired of these PS API changes...

**Review by sergio-teruel — APPROVED** [review]
@hugosantosred  Can you extend this changes to v 9.0 too?

**Comment by simahawk** [comment]
in v9 Guewen improved this part using a new unit like this https://github.com/OCA/connector-prestashop/commit/74755865fe4d6104b256d72a0ede1b6366d0f717
I think you can backport the improvement and port the new version support to v9

**Comment by pedrobaeza** [comment]
Merging this to have at least the change in v8.

**Pull request merged**
