### PR TITLE
[14][FIX] put demo backend in demo data

### PR DESCRIPTION
**Pull request by florian-dacosta**
@flotho @hailangvn @jesusVMayor

### CODE REVIEW

**Review by hailangvn — APPROVED** [review]
LGTM

**Review by flotho — APPROVED** [review]
indeed !
thanks

**Comment by flotho** [comment]
could we expect a merge today ?

**Comment by flotho** [comment]
hi @OCA/connector-prestashop-maintainers , any chance to be merged ?

**Comment by bguillot** [comment]
Thanks:

/ocabot merge patch

**Pull request merged**
